### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by yomp-admin** [Scrut1ny/VM-Undetected#1]
Can we have an installation guide please?

**Comment by mrlunt007** [comment]
> Can we have an installation guide please?

I second this notion please

**Comment by Scrut1ny** [comment]
This repo is not anywhere near complete yet, I still need to add a lot.

**Comment by igorfcouto** [comment]
Dude I have been trying to do the same thing but to make it work for proctorU so I can get through my last three semesters of university. I know of one person that apparently used OWASP to bypass proctorU since they also use GuardianBrowser. Would be happy to help in any way I can since I have exams coming up in two weeks 🫡

**Comment by igorfcouto** [comment]
Hopefully this could be of some help. 

https://youtu.be/HhMJUwVnHWc?si=7R2FbaC5rIZwWfb0

From my understanding proctorU does an initial system check for VM machine and then also runs a script right that the employees have while lastly making students use a lockdown browser called Guardian Browser that can also detect VM machines I believe. 

OWASP anti detect is what the guy that claims he was able to bypass it is using. 

https://guardian.meazurelearning.com/

**Comment by Scrut1ny** [comment]
If you're really into this and have some useful knowledge and would like to help I would appreciate it a lot. Idk if you'd like to communicate via some other platform so we could talk easier and work on this. I'd love to get a undetectable bypass working school and games. I'll definitely look into what you provide and add anything useful.

**Comment by igorfcouto** [comment]
Yeah i'd be happy to help out and i can definitely communicate somewhere else. My telegram username is @igorcoutooo just let me know if you dont have telegram and I can try to get my details to you in a more private way through somewhere else

**Comment by Scrut1ny** [comment]
I don't personally use telegram, I'll just give you my discord: 0x115#2564

**Comment by igorfcouto** [comment]
> I don't personally use telegram, I'll just give you my discord: **0x115#2564**

Request sent 🫡

**Comment by Mr-Nobody1** [comment]
Hi, were you able to build a version to bypass the proctorU? if yes, can you help me out?

**Comment by Mr-Nobody1** [comment]
> #2564

Can you send me a request on discord? my name is    .cybersenpai

**Comment by Scrut1ny** [comment]
> Hi, were you able to build a version to bypass the proctorU? if yes, can you help me out?

Yes I was able to, and I sent you a friend request on discord.

**Comment by killcilent1** [comment]
Hi, sorry to bother you. Could you add me on Discord too? I tried to find you but couldn't. Could I ask you some questions about Hypervisor-Phantom?
My discord is : codeislikemywife_123

**Comment by Scrut1ny** [comment]
> Hi, sorry to bother you. Could you add me on Discord too? I tried to find you but couldn't. Could I ask you some questions about Hypervisor-Phantom? My discord is : codeislikemywife_123

Yes, I gotcha.

**Comment by Abraxas2104** [comment]
@Scrut1ny I need help in setting this up for Proctoru mind helping me out?

**Comment by Scrut1ny** [comment]
> @Scrut1ny I need help in setting this up for Proctoru mind helping me out?

I don't have time to currently, I'm very busy. The content I and steps I provide should be enough and work. I personally recommend using QEMU/KVM always, but vbox or vmware might work also. It's just trial and error, you need to figure out which hypervisor you're going to need for what software. All hypervisors have their pros and cons.
